### ISSUE TITLE
inpファイルが似ている場合

### ISSUE THREAD

**Issue by bridgelab-omu** [kaede-cycy/Data-Processing#5]
inpファイルが似ている場合，2個目のinpも指定フォルダに移動される
あとの解析は止まられる．

**Comment by ChenYu-K** [comment]
Queuedしているファイルは進行中のJobの名前とほぼ同じ場合，
例えば，`A1-B2-C3.inp` and `A1-B2-C3-1.inp`　は同じファイルと認識してくれる.

**Comment by ChenYu-K** [comment]
理由があって，名前の近似度確認は100%にしたくないため，

近似度100%になると，以下のようなエラーファイルは一緒に持っていかれないため．
とりあえず保留．

![image](https://user-images.githubusercontent.com/71476156/176811103-dc24398d-146e-4503-86fb-a1044fbb3ff3.png)
